# List of stages for jobs, and their order of execution
stages:
  - test
  - build
  - package
  - upload
  - release

variables:
  # Package version can only contain numbers (0-9), and dots (.).
  # Must be in the format of X.Y.Z, i.e. should match /\A\d+\.\d+\.\d+\z/ regular expresion.
  # See https://docs.gitlab.com/ee/user/packages/generic_packages/#publish-a-package-file
  ZIP: $CI_PROJECT_NAME.zip

  PACKAGE_VERSION: $CI_COMMIT_TAG
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${PACKAGE_VERSION}"

  GIT_SUBMODULE_STRATEGY: normal
  GIT_SUBMODULE_FORCE_HTTPS: "true"

.release_job:
  rules:
    # Only execute when a valid version tag like 1.0, 2.3-dev or similar is given
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^[0-9]+[.][0-9]+([.][0-9]+)?([-a-z])*$/

phpunit:
  stage: test
  image: codeccoop/wp-test
  before_script:
    - nohup docker-entrypoint.sh mariadbd 2>&1 >/dev/null &
    - composer -q install
    - sleep 5
    - chmod a+x bin/*
    - bin/install-wp-tests.sh
    - bin/download-test-deps.sh
  script:
    - vendor/bin/phpunit -c phpunit.xml.dist
  rules:
    # Only execute when a valid version tag like 1.0, 2.3-dev or similar is given
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^[0-9]+[.][0-9]+([.][0-9]+)?([-a-z])*$/
    # Run always on MR pointing to master
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

build:
  extends: .release_job
  stage: build
  image: node:latest
  script:
    - find src -exec sed -i "s/http-bridge/forms-bridge/g" {} \;
    - npm install && npm run build
    - rm -rf node_modules
  artifacts:
    paths:
      - forms-bridge/assets/plugin.bundle.js

package:
  extends: .release_job
  image: codeccoop/wp-cli:latest
  stage: package
  script:
    - find forms-bridge/deps/plugin -name '*.php' -exec sed -i "s/wpct-plugin/forms-bridge/g" {} \;
    - find forms-bridge -name '*.php' -exec sed -i "s/wpct_plugin_/forms_bridge_plugin_/g" {} \;
    - find forms-bridge -name "*.php" -exec sed -i 's/WPCT_PLUGIN/FORMS_BRIDGE\\Common/g' {} \;
    - find forms-bridge/deps/http -name '*.php' -exec sed -i "s/http-bridge/forms-bridge/g" {} \;
    - find forms-bridge -name '*.php' -exec sed -i "s/http_bridge_/forms_bridge_http_/g" {} \;
    - find forms-bridge -name "*.php" -exec sed -i 's/HTTP_BRIDGE_/FORMS_BRIDGE_HTTP_/g' {} \;
    - find forms-bridge -name '*.php' -exec sed -i 's/HTTP_BRIDGE/FORMS_BRIDGE\\Http/g' {} \;
    - wp dist-archive forms-bridge ./$ZIP
  artifacts:
    paths:
      - $ZIP

upload:
  extends: .release_job
  stage: upload
  image: curlimages/curl:latest
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
      --upload-file ${ZIP} \
      ${PACKAGE_REGISTRY_URL}/${ZIP}

release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  extends: .release_job
  stage: release
  image: gitlab/glab:latest
  variables:
    GITLAB_HOST: "$CI_SERVER_URL"
  script:
    - glab auth login --job-token $CI_JOB_TOKEN --hostname $CI_SERVER_HOST --api-protocol $CI_SERVER_PROTOCOL
    - |
      glab release create $CI_COMMIT_TAG --name "Release $CI_COMMIT_TAG" \
        --assets-links "[{\"name\":\"${ZIP}\",\"url\":\"${PACKAGE_REGISTRY_URL}\/${ZIP}\",\"link_type\":\"package\",\"direct_asset_path\":\"\/plugins\/bridges\/${ZIP}\"}]"
